sudo: required

services:
  - docker
before_install:
  #- docker build -t sputtaiah/react-test -f ./client/Dockerfile.dev ./client
  # this user name should match with the dockerhub username! otherwise it will fail in following steps
  - docker build -t sathyajith91/react-test -f ./client/Dockerfile.dev ./client

script:
  #- docker run sputtaiah/react-test npm test -- --coverage #-- --coverage is to exit after the test is com[pleted] with status 0 0r 1.
  - docker run -e CI=true sathyajith91/react-test npm test

after_success:
  - docker build -t sathyajith91/multi-client ./client
  - docker build -t sathyajith91/multi-nginx ./nginx
  - docker build -t sathyajith91/multi-server ./server
  - docker build -t sathyajith91/multi-worker ./worker



  #log in to our docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push sathyajith91/multi-client
  - docker push sathyajith91/multi-nginx
  - docker push sathyajith91/multi-server
  - docker push sathyajith91/multi-worker
